---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script><script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" type="text/javascript"></script><script src="https://cdn.jsdelivr.net/npm/vega@5.25.0" type="text/javascript"></script><script src="https://cdn.jsdelivr.net/npm/vega-lite@5.16.3" type="text/javascript"></script><script src="https://cdn.jsdelivr.net/npm/vega-embed@6.22.2" type="text/javascript"></script>

# Fibonacci Sequence Function


::: {.callout-note}
## OUT
```
sut/fib
[#object[sun.nio.fs.UnixPath 0x21b40343 /Users/lukezeitlin/claymer/example] #object[sun.nio.fs.UnixPath 0x1494fec5 /Users/lukezeitlin/claymer/example/example/core.clj]]
{:path #object[sun.nio.fs.UnixPath 0x6d432ce0 example/core.clj], :line 3}
[#object[sun.nio.fs.UnixPath 0x78dbe2fa /Users/lukezeitlin/claymer/example] #object[sun.nio.fs.UnixPath 0x7605aa82 /Users/lukezeitlin/claymer/example/example/core.clj]]

```
:::



```{=html}
<a href="https://github.com/larzeitlin/claymer/blob/main/example/core.clj#L3">example.core/fib</a>
```


### `fib`
`[n]`

Takes a non-negative integer `n` and returns the nth number in the Fibonacci sequence.


## Rich comments from `example.core`


```{=html}
<div><p>(</p><div class="clay-sequential" style="margin-left:10%;width:110%;"><div><pre><code class="sourceCode language-clojure source-clojure bg-light">;; this is an example comment
  (fib 10)
  ;; recursive
  (fib (fib 10))
  ;; functional
  (map fib (range 10))</code></pre></div></div><p>)</p></div>
```



## Examples:
Produces nth number in the fibonacci sequence:


::: {.sourceClojure}
```clojure
(deftest fib-test
  (testing
   (is (= (sut/fib 0) 0)))
  (testing
   (is (= (sut/fib 12) 144)))
  (testing
   (is (= (sut/fib 69) 117669030460994))))
```
:::



```{=html}
<pre><code style="background-color:#92C648;">PASS: (= 0 0)</code><code style="background-color:#92C648;">PASS: (= 144 144)</code><code style="background-color:#92C648;">PASS: (= 117669030460994 117669030460994)</code></pre>
```


Negitive numbers are out of bounds.


::: {.sourceClojure}
```clojure
(deftest fib-neg-n-out-of-range-test
  (is
   (try (sut/fib -1)
        (catch Exception e
          (= (type e) java.lang.IndexOutOfBoundsException)))))
```
:::



```{=html}
<pre><code style="background-color:#92C648;">PASS: true</code></pre>
```



## Properties

### Parity Invarient
Every third Fibonacci number is even.
This is because an odd + even = odd so we get the cycle:
```
0+1=1 -> 1+1=2 -> 1+2=3 -> ...
E+O=O -> O+O=E -> O+E=O -> ...
```


::: {.sourceClojure}
```clojure
(def parity-invariant
  (prop/for-all
   [v gen/pos-int]
   (let [fib-number (sut/fib v)]
     (if (zero? (rem v 3))
       (even? fib-number)
       (odd? fib-number)))))
```
:::



::: {.sourceClojure}
```clojure
(tc/quick-check 10000 parity-invariant)
```
:::



::: {.printedClojure}
```clojure
{:result true,
 :pass? true,
 :num-tests 10000,
 :time-elapsed-ms 60,
 :seed 1772375518663}

```
:::



## Performance Comparison
Below we compare the efficient iterative `fib` against a naive recursive
`fib-naive` implementation across a range of input sizes. The naive version
has exponential time complexity, so its execution time grows dramatically.


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"$schema":"https:\/\/vega.github.io\/schema\/vega-lite\/v5.json","title":"Fibonacci Performance: Iterative vs Naive Recursive","width":600,"height":400,"data":{"values":[{"n":0,"time-ms":0.010834,"implementation":"fib (iterative)"},{"n":1,"time-ms":0.002791,"implementation":"fib (iterative)"},{"n":2,"time-ms":5.84E-4,"implementation":"fib (iterative)"},{"n":3,"time-ms":5.0E-4,"implementation":"fib (iterative)"},{"n":4,"time-ms":5.0E-4,"implementation":"fib (iterative)"},{"n":5,"time-ms":5.41E-4,"implementation":"fib (iterative)"},{"n":6,"time-ms":6.67E-4,"implementation":"fib (iterative)"},{"n":7,"time-ms":6.67E-4,"implementation":"fib (iterative)"},{"n":8,"time-ms":0.002166,"implementation":"fib (iterative)"},{"n":9,"time-ms":8.75E-4,"implementation":"fib (iterative)"},{"n":10,"time-ms":8.75E-4,"implementation":"fib (iterative)"},{"n":11,"time-ms":9.59E-4,"implementation":"fib (iterative)"},{"n":12,"time-ms":0.001125,"implementation":"fib (iterative)"},{"n":13,"time-ms":0.0025,"implementation":"fib (iterative)"},{"n":14,"time-ms":0.00125,"implementation":"fib (iterative)"},{"n":15,"time-ms":0.00125,"implementation":"fib (iterative)"},{"n":16,"time-ms":0.015834,"implementation":"fib (iterative)"},{"n":17,"time-ms":0.0015,"implementation":"fib (iterative)"},{"n":18,"time-ms":0.0015,"implementation":"fib (iterative)"},{"n":19,"time-ms":0.003125,"implementation":"fib (iterative)"},{"n":20,"time-ms":0.001584,"implementation":"fib (iterative)"},{"n":21,"time-ms":0.001666,"implementation":"fib (iterative)"},{"n":22,"time-ms":0.002917,"implementation":"fib (iterative)"},{"n":23,"time-ms":0.003916,"implementation":"fib (iterative)"},{"n":24,"time-ms":0.003708,"implementation":"fib (iterative)"},{"n":25,"time-ms":0.002458,"implementation":"fib (iterative)"},{"n":26,"time-ms":0.003792,"implementation":"fib (iterative)"},{"n":27,"time-ms":0.002084,"implementation":"fib (iterative)"},{"n":28,"time-ms":0.003334,"implementation":"fib (iterative)"},{"n":29,"time-ms":0.00225,"implementation":"fib (iterative)"},{"n":30,"time-ms":0.00375,"implementation":"fib (iterative)"},{"n":0,"time-ms":0.008417,"implementation":"fib-naive (recursive)"},{"n":1,"time-ms":0.00125,"implementation":"fib-naive (recursive)"},{"n":2,"time-ms":0.027958,"implementation":"fib-naive (recursive)"},{"n":3,"time-ms":0.001,"implementation":"fib-naive (recursive)"},{"n":4,"time-ms":0.001625,"implementation":"fib-naive (recursive)"},{"n":5,"time-ms":0.002709,"implementation":"fib-naive (recursive)"},{"n":6,"time-ms":0.0045,"implementation":"fib-naive (recursive)"},{"n":7,"time-ms":0.008083,"implementation":"fib-naive (recursive)"},{"n":8,"time-ms":0.012667,"implementation":"fib-naive (recursive)"},{"n":9,"time-ms":0.021833,"implementation":"fib-naive (recursive)"},{"n":10,"time-ms":0.031583,"implementation":"fib-naive (recursive)"},{"n":11,"time-ms":0.053292,"implementation":"fib-naive (recursive)"},{"n":12,"time-ms":0.068375,"implementation":"fib-naive (recursive)"},{"n":13,"time-ms":0.0965,"implementation":"fib-naive (recursive)"},{"n":14,"time-ms":0.112708,"implementation":"fib-naive (recursive)"},{"n":15,"time-ms":0.070916,"implementation":"fib-naive (recursive)"},{"n":16,"time-ms":0.115333,"implementation":"fib-naive (recursive)"},{"n":17,"time-ms":0.201584,"implementation":"fib-naive (recursive)"},{"n":18,"time-ms":0.295333,"implementation":"fib-naive (recursive)"},{"n":19,"time-ms":0.478083,"implementation":"fib-naive (recursive)"},{"n":20,"time-ms":0.757375,"implementation":"fib-naive (recursive)"},{"n":21,"time-ms":1.137209,"implementation":"fib-naive (recursive)"},{"n":22,"time-ms":1.188459,"implementation":"fib-naive (recursive)"},{"n":23,"time-ms":1.927792,"implementation":"fib-naive (recursive)"},{"n":24,"time-ms":3.152041,"implementation":"fib-naive (recursive)"},{"n":25,"time-ms":0.822583,"implementation":"fib-naive (recursive)"},{"n":26,"time-ms":0.799708,"implementation":"fib-naive (recursive)"},{"n":27,"time-ms":1.316916,"implementation":"fib-naive (recursive)"},{"n":28,"time-ms":2.15725,"implementation":"fib-naive (recursive)"},{"n":29,"time-ms":3.515333,"implementation":"fib-naive (recursive)"},{"n":30,"time-ms":5.719,"implementation":"fib-naive (recursive)"}]},"mark":{"type":"line","point":true},"encoding":{"x":{"field":"n","type":"quantitative","title":"n"},"y":{"field":"time-ms","type":"quantitative","title":"Time (ms)"},"color":{"field":"implementation","type":"nominal","title":"Implementation"}}});</script></div>
```



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/larzeitlin/claymer/blob/main/example/test/example/core_test.clj">example/test/example/core_test.clj</a></small></small></pre></div>
```